# https://github.com/varlociraptor/varlociraptor-methylation-evaluation

platforms: [Illumina_pe, PacBio]
# platforms: [Nanopore]

ref_tools:
  # Chose from: bismark, bisSNP, methylDackel, bsMap
  Illumina_pe: [bismark, bisSNP, methylDackel, bsMap]
  # Chose from: pb_CpG_tools
  PacBio: [pb_CpG_tools]
  # Chose from: modkit
  Nanopore: [modkit]

sample:
  species: "homo_sapiens"
  datatype: "dna"
  build: "GRCh38"
  release: "110"
  chromosome: "21"

# base_dir: "~/Documents/Promotion/"
# varlo_path: "~/Documents/Promotion/varlociraptor/"
# pipeline_path: "~/Documents/Promotion/varlociraptor-methylation-evaluation/"
# methylFastQ_path: "~/Documents/Promotion/MethylFASTQ/"

# Gibt an, auf wie viele scatter plots wir unsere Ergebnisse aufteilen (je nach coverage, 10 pro coverage, letztes bekommt alle restlichen)
cov_bins: 1

base_dir: "/projects/koesterlab/benchmark-methylation/"
varlo_path: "/projects/koesterlab/benchmark-methylation/varlociraptor/"
pipeline_path: "/projects/koesterlab/benchmark-methylation/varlociraptor-methylation-evaluation/"
methylFastQ_path: "/projects/koesterlab/benchmark-methylation/MethylFASTQ/"

candidate: 40437798
max_read_length: 100000

data:
  Illumina_pe:
    # test: [SRR_test]
    TruSeq_HG002_LAB01_REP01: [SRR13050995, SRR13050996, SRR13050998]
  #   TruSeq_HG002_LAB01_REP02: [SRR13050992, SRR13050993, SRR13050994]   
  #   SPLAT_HG002_LAB01_REP01_4: [SRR13051055, SRR13051056, SRR13051057, SRR13051058]
  #   SPLAT_HG002_LAB01_REP02_4:  [SRR13051050, SRR13051051, SRR13051052, SRR13051054]
  #   MethylSeq_HG002_LAB01_REP01: [SRR13051104, SRR13051105, SRR13051106]
  #   MethylSeq_HG002_LAB01_REP02: [SRR13051101, SRR13051102, SRR13051103]
  # # EMSeq, TrueMethylOX und TrueMEthylBS gibt es je immer nur ein SRR zu 
  #   EMSeq_HG002_LAB02_REP02: [SRR13051139]
  #   EMSeq_HG002_LAB02_REP01: [SRR13051140]
  #   EMSeq_HG002_LAB01_REP02: [SRR13051141]
  #   EMSeq_HG002_LAB01_REP01: [SRR13051142]
  #   TrueMethylOX_HG002_LAB01_REP02: [SRR13051230]
  #   TrueMethylOX_HG002_LAB01_REP01: [SRR13051231, SRR13051232]
  #   TrueMethylBS_HG002_LAB01_REP02: [SRR13051250, SRR13051251] #2023-10-25T12:57:27 fasterq-dump.3.0.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
  #   TrueMethylBS_HG002_LAB01_REP01: [SRR13051253] #2023-10-25T12:57:27 fasterq-dump.3.0.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
  Illumina_se:
    # No example data found
  PacBio:
    data1: [dummySRA_pacBio]
  Nanopore:
    data1: [dummySRA_nanopore]



dummySRA_pacBio: "https://downloads.pacbcloud.com/public/dataset/HG002-CpG-methylation-202202/HG002.GRCh38.haplotagged.bam"
dummySRA_nanopore: "https://ont-open-data.s3.amazonaws.com/gm24385_mod_2021.09/extra_analysis/all.bam"

bedGraphs_HG002:
  - GSM5649436_TruSeq_HG002_LAB01_REP02
  - GSM5649437_TruSeq_HG002_LAB01_REP01
  - GSM5649458_SPLAT_HG002_LAB01_REP02
  - GSM5649459_SPLAT_HG002_LAB01_REP01
  - GSM5649479_MethylSeq_HG002_LAB01_REP02
  - GSM5649480_MethylSeq_HG002_LAB01_REP01
  - GSM5649515_EMSeq_HG002_LAB02_REP02
  - GSM5649517_EMSeq_HG002_LAB02_REP01
  - GSM5649518_EMSeq_HG002_LAB01_REP02
  - GSM5649520_EMSeq_HG002_LAB01_REP01
  - GSM5649543_TrueMethylOX_HG002_LAB01_REP02
  - GSM5649545_TrueMethylOX_HG002_LAB01_REP01
  - GSM5649565_TrueMethylBS_HG002_LAB01_REP02
  - GSM5649567_TrueMethylBS_HG002_LAB01_REP01
  - GSM5649568_EPIC_HG002_LAB01_REP02
  - GSM5649573_EPIC_HG002_LAB01_REP01
