###################################### DATA ##################################################

# Genome information
sample:
  species: "homo_sapiens"
  datatype: "dna"
  build: "GRCh38"
  release: "110"

# Choose specific chromosome for evaluation
seq_platforms: 
  PacBio: 21
  Illumina_pe: 21
  Nanopore: 21

# Chrom for simulated reads. Must be given even if we do not want to simulate since it is used in input files. 
# TODO: Fix this
# simulated_chrom: 21

# Define reference tools for comparision against varlociraptor results
ref_tools:
  # Chose from: bismark, bisSNP, methylDackel, bsMap
  # Illumina_pe: [bismark, bsMap, methylDackel, bisSNP]
  multi_sample: []
  Illumina_pe: [methylDackel]
  # Illumina_pe: [methylDackel]
  # Illumina_pe: [bismark]
  # Chose from: pb_CpG_tools
  PacBio: [pb_CpG_tools]
  # Chose from: modkit
  Nanopore: [modkit]


# Define minimum mapping quality to keep in alignment
min_mapping_quality: 10
# How many reads should be simulated
num_simulated_reads: 100000

protocols: 
  multi_sample: [REP]
  Illumina_pe: [TruSeq_HG002_LAB01, EMSeq_HG002_LAB02, EMSeq_HG002_LAB01, TrueMethylOX_HG002_LAB01, TrueMethylBS_HG002_LAB01, SPLAT_HG002_LAB01, MethylSeq_HG002_LAB01]
  # Illumina_pe: [TruSeq_HG002_LAB01, SPLAT_HG002_LAB01]
  PacBio: [REP]
  Nanopore: [REP]
# protocols: [TruSeq_HG002_LAB01]
# protocol replicates must end on "REP01" and "REP02"
data:
  Illumina_pe:
    # simulated_data: []
    TruSeq_HG002_LAB01_REP01: [SRR13050995, SRR13050996, SRR13050998]
    TruSeq_HG002_LAB01_REP02: [SRR13050992, SRR13050993, SRR13050994]
    # For downloading:  It's called SPLAT_HG002_LAB01_REP01_4 but this makes problems with the compare samples script
    SPLAT_HG002_LAB01_REP01: [SRR13051055, SRR13051056, SRR13051057, SRR13051058]
    SPLAT_HG002_LAB01_REP02:  [SRR13051050, SRR13051051, SRR13051052, SRR13051054]
    MethylSeq_HG002_LAB01_REP01: [SRR13051104, SRR13051105, SRR13051106]
    MethylSeq_HG002_LAB01_REP02: [SRR13051101, SRR13051102, SRR13051103]
    # EMSeq, TrueMethylOX und TrueMEthylBS gibt es je immer nur ein SRR zu 
    EMSeq_HG002_LAB02_REP02: [SRR13051139]
    EMSeq_HG002_LAB02_REP01: [SRR13051140]
    EMSeq_HG002_LAB01_REP02: [SRR13051141]
    EMSeq_HG002_LAB01_REP01: [SRR13051142]
    TrueMethylOX_HG002_LAB01_REP02: [SRR13051230]
    TrueMethylOX_HG002_LAB01_REP01: [SRR13051231, SRR13051232]
    TrueMethylBS_HG002_LAB01_REP02: [SRR13051250, SRR13051251] #2023-10-25T12:57:27 fasterq-dump.3.0.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
    TrueMethylBS_HG002_LAB01_REP01: [SRR13051253] #2023-10-25T12:57:27 fasterq-dump.3.0.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
  Illumina_se:
    # No example data found
  PacBio:
    # data1: [dummySRA_pacBio]
    REP01: [pb_rep1]
    REP02: [pb_rep2]
    REP03: [pb_rep3]
  Nanopore:
    # data1: [dummySRA_nanopore]
    REP01: [np_rep1]
    REP02: [np_rep2]
  multi_sample:
    REP01: [dummy_rep1]
    REP02: [dummy_rep2]

# For more information visit: https://downloads.pacbcloud.com/public/dataset/HG002-CpG-methylation-202202/
dummySRA_pacBio: "https://downloads.pacbcloud.com/public/dataset/HG002-CpG-methylation-202202/HG002.GRCh38.haplotagged.bam"

# Here could be more pacbio data:
# https://downloads.pacbcloud.com/public/2024Q4/Vega/HG002/

# Ã¼berblick PacBio Data
# https://www.pacb.com/connect/datasets/ Diese geben mir die folgenden datasets:

# Here I have two pacbio replicates:
# https://downloads.pacbcloud.com/public/revio/2024Q4/WGS/GIAB_trio/

# Here I have three:
# https://downloads.pacbcloud.com/public/revio/2022Q4/?utm_source=Website&utm_medium=webpage&utm_term=HomoSapiens-GIAB-trio-HG002-4&utm_content=datasets&utm_campaign=0000-Website-Leads
pb_rep1: https://downloads.pacbcloud.com/public/revio/2022Q4/HG002-rep1/analysis/HG002.m84011_220902_175841_s1.GRCh38.bam
pb_rep2: https://downloads.pacbcloud.com/public/revio/2022Q4/HG002-rep2/analysis/HG002.m84005_220919_232112_s2.GRCh38.bam
pb_rep3: https://downloads.pacbcloud.com/public/revio/2022Q4/HG002-rep3/analysis/HG002.m84005_220827_014912_s1.GRCh38.bam

# For more information look at: https://epi2me.nanoporetech.com/gm24385-5mc/
dummySRA_nanopore: "https://ont-open-data.s3.amazonaws.com/gm24385_mod_2021.09/extra_analysis/all.bam"
np_rep1: https://42basepairs.com/download/s3/ont-open-data/giab_2025.01/basecalling/hac/HG002/PAW70337/calls.sorted.bam
np_rep2: https://42basepairs.com/download/s3/ont-open-data/giab_2025.01/basecalling/hac/HG002/PAW71238/calls.sorted.bam
# Here could be another dataset:
# https://epi2me.nanoporetech.com/giab-2025.01/

bedGraphs_HG002:
  - GSM5649436_TruSeq_HG002_LAB01_REP02
  - GSM5649437_TruSeq_HG002_LAB01_REP01
  - GSM5649458_SPLAT_HG002_LAB01_REP02
  - GSM5649459_SPLAT_HG002_LAB01_REP01
  - GSM5649479_MethylSeq_HG002_LAB01_REP02
  - GSM5649480_MethylSeq_HG002_LAB01_REP01
  - GSM5649515_EMSeq_HG002_LAB02_REP02
  - GSM5649517_EMSeq_HG002_LAB02_REP01
  - GSM5649518_EMSeq_HG002_LAB01_REP02
  - GSM5649520_EMSeq_HG002_LAB01_REP01
  - GSM5649543_TrueMethylOX_HG002_LAB01_REP02
  - GSM5649545_TrueMethylOX_HG002_LAB01_REP01
  - GSM5649565_TrueMethylBS_HG002_LAB01_REP02
  - GSM5649567_TrueMethylBS_HG002_LAB01_REP01
  - GSM5649568_EPIC_HG002_LAB01_REP02
  - GSM5649573_EPIC_HG002_LAB01_REP01



###################################### METH CALLING ##################################################

# Define minimum mapping quality to keep in alignment
min_mapping_quality: 10
# How many reads should be simulated
num_simulated_reads: 10000
# Number of scatter gather items
scatter_number: 20
# Rough estimate for maximum re0ad length. This is use to shorten the length of the candidate files
max_read_length: 50000
fdr_alpha: [0.01, 0.05, 0.1, 1.0]

###################################### PLOTS ##################################################
heatmap_bin_size: 5
# Choose frome png, svg, html
plot_type: png
# Define threshhold for false positive cutoff
prob_pres_threshhold: 0.95
prob_absent_threshhold: 0.95
# Define the minimum percantage  of methylation to be considered as a methylated site
meth_threshold: 5

# Choose between "ratio" and "posterior" for different computation methods of methylation rates in the result plots
meth_type: posterior


# Define number of coverage bins. Pipeline will create plots for each coverage bin.
cov_bins: 
  Illumina_pe: 5
  PacBio: 5
  Nanopore: 5
# Size of each coverage bin. Last bin gets all remaining coverages.
cov_bin_size:
  Illumina_pe: 10
  PacBio: 20
  Nanopore: 20

# Define the correlation method for the comparision of the different samples
# Choose any number from: pearson, spearman, rmse, mape, ccc (concordance correlation coefficient)
correlation_methods: [rmse, mape, ccc]