###################################### DATA ##################################################
# bcftools view -r 21:7800000-8000000 resources/minimal/candidates.bcf -Oz -o resources/minimal/candidates_new.bcf
# samtools view -b     /projects/koesterlab/benchmark-methylation/varlociraptor-methylation-evaluation/resources/PacBio/REP01/pb_rep1/alignment.bam     chr21:7800000-8000000     > /projects/koesterlab/benchmark-methylation/varlociraptor-methylation-evaluation/resources/PacBio/REP01/pb_rep1/alignment_minimal.bam

# Genome information
sample:
  species: "homo_sapiens"
  datatype: "dna"
  build: "GRCh38"
  release: "110"

# Choose specific chromosome for evaluation
seq_platforms: 
  Illumina_pe: minimal
  PacBio: minimal
  # Nanopore: 21

# Define reference tools for comparision against varlociraptor results
ref_tools:
  # Chose from: bismark, bisSNP, methylDackel, bsMap
  # Illumina_pe: [bismark, bsMap, methylDackel, bisSNP]
  Illumina_pe: [methylDackel]
  # Chose from: pb_CpG_tools
  PacBio: [pb_CpG_tools]
  # Chose from: modkit
  # Nanopore: [modkit]
  # This needs to be an empty list
  # multi_sample: []


samples: 
  Illumina_pe: [minimal]
  PacBio: [minimal]
  # Nanopore: [minimal]
  # multi_sample: [minimal]
data:
  Illumina_pe:
    minimal01: [rep01]
    minimal02: [rep02]
  PacBio:
    minimal01: [rep01]
    minimal02: [rep02]
  # Nanopore:
  #   REP01: [minimal_rep1]
  #   REP02: [minimal_rep2]
  # multi_sample:
  #   REP01: [minimal_rep1]
  #   REP02: [minimal_rep2]



###################################### METH CALLING ##################################################

# Define minimum mapping quality to keep in alignment
min_mapping_quality: 10
# Number of scatter gather items (used for parallelization of varlociraptor methylation calling)
scatter_number: 1
# Define FDR alpha levels for varlociraptor methylation filtering
fdr_alpha: [0.01]

###################################### PLOTS ##################################################

heatmap_bin_size: 5
# Choose frome png, svg, html
plot_type: png
# Define the correlation method for the comparision of the different samples
# Choose any number from: pearson, spearman, rmse, ccc (concordance correlation coefficient), adjusted_mape
correlation_methods: [mape]